import appConfig from "@/config/app.config";
import AuthProvider from "@/providers/AuthProvider";

export const metadata = {
  title: appConfig.name,
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
